export const countries = [
    { value: "United States", label: "United States" },
    { value: "Canada", label: "Canada" },
    { value: "Australia", label: "Australia" },
    { value: "Germany", label: "Germany" },
    { value: "India", label: "India" },
    { value: "Brazil", label: "Brazil" },
    { value: "United Kingdom", label: "United Kingdom" },
    { value: "France", label: "France" },
    { value: "Japan", label: "Japan" },
    { value: "Mexico", label: "Mexico" },
    { value: "China", label: "China" },
    { value: "Russia", label: "Russia" },
    { value: "Italy", label: "Italy" },
    { value: "South Africa", label: "South Africa" },
    { value: "South Korea", label: "South Korea" },
    { value: "New Zealand", label: "New Zealand" },
    { value: "Spain", label: "Spain" },
    { value: "Netherlands", label: "Netherlands" },
    { value: "Switzerland", label: "Switzerland" },
    { value: "Sweden", label: "Sweden" },
    { value: "Norway", label: "Norway" },
    { value: "Denmark", label: "Denmark" },
    { value: "Finland", label: "Finland" },
    { value: "Ireland", label: "Ireland" },
    { value: "Belgium", label: "Belgium" },
    { value: "Argentina", label: "Argentina" },
    { value: "Chile", label: "Chile" },
    { value: "Colombia", label: "Colombia" },
    { value: "Peru", label: "Peru" },
    { value: "Venezuela", label: "Venezuela" },
    { value: "Egypt", label: "Egypt" },
    { value: "Saudi Arabia", label: "Saudi Arabia" },
    { value: "United Arab Emirates", label: "United Arab Emirates" },
    { value: "Turkey", label: "Turkey" },
    { value: "Indonesia", label: "Indonesia" },
    { value: "Malaysia", label: "Malaysia" },
    { value: "Thailand", label: "Thailand" },
    { value: "Vietnam", label: "Vietnam" },
    { value: "Philippines", label: "Philippines" },
    { value: "Singapore", label: "Singapore" },
    { value: "Pakistan", label: "Pakistan" },
    { value: "Bangladesh", label: "Bangladesh" },
    { value: "Nigeria", label: "Nigeria" },
    { value: "Kenya", label: "Kenya" },
    { value: "Ghana", label: "Ghana" },
    { value: "Ethiopia", label: "Ethiopia" },
    { value: "Morocco", label: "Morocco" },
    { value: "Poland", label: "Poland" },
    { value: "Ukraine", label: "Ukraine" },
  ];
  